version: "3.8"

services:
  db:
    image: mysql:5.7  # Image officielle de MySQL
    container_name: mysql_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql  # Volume pour stocker les données MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass

  wordpress:
    image: wordpress:latest  # Image officielle de WordPress
    container_name: wordpress_app
    depends_on:
      - db  # Démarre après le service db
    ports:
      - "8080:80"  # Port d’accès depuis le navigateur
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:  # Volume persistant pour la base de données
